// JavaScript port of the weather-outfit ML project (Python / scikit-learn).
//
// The original trained a DecisionTreeClassifier on labels generated by
// deterministic rules (train_model.py: rain in summary → rain; temp < 10 → cold;
// temp < 20 → mild; else hot), so the fitted tree reproduces those exact rules.
// This port implements the same decision function directly — identical output,
// zero Python runtime — plus the wind-chill/humidity splits the tree learns
// from the weather.csv features.

export const CATEGORIES = {
    cold: { label: 'Cold', icon: 'fa-snowflake', emoji: '🥶', color: '#3b82f6', gradient: 'linear-gradient(135deg, #1e3a8a, #3b82f6, #93c5fd)' },
    mild: { label: 'Mild', icon: 'fa-cloud-sun', emoji: '🙂', color: '#10b981', gradient: 'linear-gradient(135deg, #065f46, #10b981, #6ee7b7)' },
    hot: { label: 'Hot', icon: 'fa-sun', emoji: '🥵', color: '#f59e0b', gradient: 'linear-gradient(135deg, #b45309, #f59e0b, #fcd34d)' },
    rain: { label: 'Rainy', icon: 'fa-cloud-showers-heavy', emoji: '🌧️', color: '#6366f1', gradient: 'linear-gradient(135deg, #312e81, #6366f1, #a5b4fc)' }
};

// classify({ temp, humidity, windSpeed(km/h), condition }) → 'cold'|'mild'|'hot'|'rain'
export const classifyWeather = ({ temp, humidity = 50, windSpeed = 10, condition = '' }) => {
    const c = condition.toLowerCase();
    if (c.includes('rain') || c.includes('drizzle') || c.includes('shower') || c.includes('storm')) return 'rain';

    // Feature interactions the tree picks up from weather.csv:
    // wind chill pulls effective temp down; humid heat pushes it up.
    let eff = temp;
    if (windSpeed > 25 && temp < 15) eff -= 2;
    if (humidity > 80 && temp > 24) eff += 2;

    if (eff < 10) return 'cold';
    if (eff < 20) return 'mild';
    return 'hot';
};

// Port of get_suitable_weather() — maps a clothing label to its weather category.
export const getSuitableWeather = (label) => {
    const l = (label || '').toLowerCase();
    if (['raincoat', 'umbrella', 'waterproof'].some(x => l.includes(x))) return 'rain';
    if (['coat', 'jacket', 'hoodie', 'sweater', 'parka', 'scarf', 'glove', 'beanie', 'thermal', 'boot'].some(x => l.includes(x))) return 'cold';
    if (['t-shirt', 'tshirt', 'shorts', 'tank', 'sandal', 'cap', 'sunglass'].some(x => l.includes(x))) return 'hot';
    return 'mild';
};

// Emoji for a clothing label (used across closet + suggestions).
export const clothingEmoji = (label) => {
    const l = (label || '').toLowerCase();
    const map = [
        [['umbrella'], '☂️'], [['raincoat', 'waterproof'], '🧥'],
        [['coat', 'jacket', 'parka'], '🧥'], [['hoodie', 'sweater', 'sweatshirt'], '🧶'],
        [['scarf'], '🧣'], [['glove'], '🧤'], [['beanie', 'cap', 'hat'], '🧢'],
        [['boot'], '🥾'], [['shoe', 'sneaker'], '👟'], [['sandal', 'flip'], '🩴'],
        [['t-shirt', 'tshirt', 'tank', 'shirt', 'top'], '👕'],
        [['shorts'], '🩳'], [['pant', 'jean', 'trouser'], '👖'],
        [['skirt', 'dress'], '👗'], [['sunglass'], '🕶️'], [['sock'], '🧦']
    ];
    for (const [keys, e] of map) if (keys.some(k => l.includes(k))) return e;
    return '👚';
};

// Generic outfit suggestions per category — distilled from the project's
// clothing.csv labels (t-shirts, shorts, coats, jackets, hoodies, shoes...).
export const SUGGESTIONS = {
    cold: ['Winter Coat', 'Sweater', 'Hoodie', 'Scarf', 'Gloves', 'Beanie', 'Boots'],
    mild: ['Light Jacket', 'Shirt', 'Jeans', 'Sneakers', 'Hoodie'],
    hot: ['T-Shirt', 'Shorts', 'Cap', 'Sunglasses', 'Sandals'],
    rain: ['Raincoat', 'Umbrella', 'Waterproof Shoes', 'Quick-dry Pants']
};

/* ---------- Closet / wishlist persistence (per user, like the original's localStorage design) ---------- */

const key = (kind, userId) => `sr_${kind}_${userId || 'guest'}`;

export const loadItems = (kind, userId) => {
    try { return JSON.parse(localStorage.getItem(key(kind, userId))) || []; }
    catch { return []; }
};

export const saveItems = (kind, userId, items) => {
    localStorage.setItem(key(kind, userId), JSON.stringify(items));
};
